# Generated by Django 3.1.1 on 2021-11-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
