# Generated by Django 3.1.1 on 2021-10-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
