# Generated by Django 3.1.1 on 2021-10-29 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_auto_20211025_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 10, 25, 0, 559337)),
        ),
        migrations.AddField(
            model_name='myuser',
            name='сreated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 10, 25, 0, 559337)),
        ),
    ]
