# Generated by Django 3.1.1 on 2021-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_auto_20211029_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='сreated_at',
            field=models.DateTimeField(),
        ),
    ]
