# Generated by Django 3.1.1 on 2021-10-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_auto_20211029_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='сreated_at',
            new_name='created_at',
        ),
    ]
