# Generated by Django 3.1.1 on 2021-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='image/profile.jpg', upload_to='images'),
        ),
    ]
