# Generated by Django 3.1.1 on 2021-11-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_auto_20211103_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='me.myuser')),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
