# Generated by Django 3.1.1 on 2021-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=300),
        ),
    ]
